[package]
name = "spicy"
version = "0.1.0"
edition = "2024"

[dependencies]
unscanny =  "0.1.0"
ndarray = 0.16.1
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }


[dev-dependencies]
rstest = "0.23.0"
insta = "1.42.1"

[profile.release]
opt-level = 3
lto = true