
[workspace]
resolver = "2"
members = [
    "crates/spicy_parser",
    "crates/spicy_simulate",
    "crates/spicy_cli",
    "fuzz",
]

[workspace.dependencies]
criterion = "0.8.1"

[profile.release]
debug = 2
