[package]
name = "spicy_parser"
version = "0.1.0"
edition = "2024"

[dependencies]
unscanny =  "0.1.0"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.16"


[dev-dependencies]
rstest = "0.23.0"
insta = "1.42.1"
serde_json = "1.0.132"